// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZx2qy1ZA0KwVzHQul6HI1ZXLciCbl_3c',
    appId: '1:1011477696119:web:5dac7a4594487aac58c072',
    messagingSenderId: '1011477696119',
    projectId: 'photoshare-98fc8',
    authDomain: 'photoshare-98fc8.firebaseapp.com',
    storageBucket: 'photoshare-98fc8.appspot.com',
    measurementId: 'G-SNJS62K7MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaCgw2iTFhiqVTK3fTvv_8aA408NvWE08',
    appId: '1:1011477696119:android:48c7b7779bc2208158c072',
    messagingSenderId: '1011477696119',
    projectId: 'photoshare-98fc8',
    storageBucket: 'photoshare-98fc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAg7GvdiDZy-0FXKWNTVYdwTWHECKf4E',
    appId: '1:1011477696119:ios:80034baf67856e7b58c072',
    messagingSenderId: '1011477696119',
    projectId: 'photoshare-98fc8',
    storageBucket: 'photoshare-98fc8.appspot.com',
    iosBundleId: 'com.example.photoShare',
  );
}
